name: New issues
on: 
  issues:
    types: [opened]
jobs:
  new-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Output issue
        run: |
          echo "Issue title - ${{ toJSON(github.event.issue.title) }}"
          echo "Issue description - ${{ toJSON(github.event.issue.body) }}"