name: New issues
on: issues
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Output issue
        run: |
          echo "Issue title - ${{ toJSON(github.event.issue.title) }}"
          echo "Issue description - ${{ toJSON(github.event.issue.description) }}"